name: Generate Stats Images

# Controls when the action will run. Triggers the workflow on push events
on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  metrics: 
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      #- uses: lowlighter/metrics@latest
      # need to use fork because of https://github.com/lowlighter/metrics/issues/1706
      - uses: gh-metrics/metrics@master
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          filename: metrics.svg
          committer_branch: generated
          repositories_skipped: "danthe1st/obsidian"
          verify: yes
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_topics: yes
          plugin_reactions: yes
          plugin_reactions_display: relative
          plugin_people: yes
          plugin_gists: yes
          plugin_lines: yes
          plugin_traffic: yes
          plugin_stargazers: yes
          plugin_achievements: yes
          plugin_notable: yes
          plugin_notable_filter: stars:>5
          plugin_notable_repositories: yes
          plugin_skyline: no
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 10871900
          plugin_stackoverflow_limit: 4
          plugin_wakatime: no
  stats:
    runs-on: ubuntu-latest
    needs: metrics
    steps:
    - uses: actions/checkout@v4
      with:
        repository: 'jstrieb/github-stats'
    - name: remove generated directory
      run: rm -rf generated
    - name: checkout this repository
      uses: actions/checkout@v4
      with:
        path: 'generated'
        ref: 'generated'
    # Run using Python 3.8 for consistency and aiohttp
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
        architecture: 'x64'

    # Cache dependencies. From:
    # https://github.com/actions/cache/blob/master/examples.md#python---pip
    - uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    # Install dependencies with `pip`
    - name: Install requirements
      run: |
        python3 -m pip install --upgrade pip setuptools wheel
        python3 -m pip install -r requirements.txt
    # Generate all statistics images
    - name: Generate images
      run: |
        python3 --version
        python3 generate_images.py
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        EXCLUDED: ${{ secrets.EXCLUDED }}
        EXCLUDED_LANGS: ${{ secrets.EXCLUDED_LANGS }}
        EXCLUDE_FORKED_REPOS: true
    - name: Overwrite generated branch
      run: |
        cd generated
        git config --global user.name "github-actions[bot]"
        git config --global user.email "actions@github.com"
        git add .
        git commit --amend --no-edit || true
        git push --force-with-lease
